# GitHub action to build LAMMPS-GUI on Linux with Qt 5.15LTS
name: "Compile and run tests with Qt 5.15LTS"

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

  workflow_dispatch:

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  build:
    name: Build with Qt 5.15LTS support enabled
    if: ${{ github.repository == 'akohlmey/lammps-gui' }}
    runs-on: ubuntu-22.04
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 20

    - name: Install extra packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
                                build-essential \
                                cmake \
                                libfontconfig1 \
                                libglu1-mesa-dev \
                                libomp-dev \
                                mesa-common-dev \
                                ninja-build \
                                qtbase5-dev \
                                libqt5charts5-dev \
                                python3-dev \
                                python3-tk \
                                xvfb \
                                imagemagick

    - name: Create Build Environment
      run: mkdir build

    - name: Building LAMMPS-GUI via CMake
      shell: bash
      run: |
        cmake -S . -B build \
              -D LAMMPS_GUI_USE_PLUGIN=yes \
              -D BUILD_DOC=no \
              -D CMAKE_CXX_STANDARD=17 \
              -D CMAKE_BUILD_TYPE=Release \
              -D ENABLE_TESTING=yes \
              -G Ninja
        cmake --build build --parallel 2

    - name: Check if LAMMPS-GUI can run at all
      shell: bash
      run: |
        build/lammps-gui --platform offscreen -v

    - name: Download pre-compiled LAMMPS shared library
      run: |
        curl -L -o build/test/liblammps.so.0 https://download.lammps.org/lammps-gui/liblammps.so.0
        chmod +x build/test/liblammps.so.0

    - name: Run Tests via CTest
      shell: bash
      run: |
        ctest --test-dir build/test -V
